name: build / mitamae-tarball

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: earthly/actions-setup@v1.0.8
        with:
          version: 0.7.20
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: "arn:aws:iam::703296234542:role/GhaIsunarabeImages"
          aws-region: ap-northeast-1

      - name: Build tarball
        working-directory: ${{ inputs.image }}
        run: |
          earthly +mitamae-tarball

      - name: Upload tarball
        working-directory: ${{ inputs.image }}
        env:
          IMAGE_NAME: ${{ inputs.image }}
        run: |
          aws s3 cp build/mitamae.tar.gz "s3://isunarabe-images/latest/${IMAGE_NAME}/mitamae.tar.gz"
